name: PHPUnit

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    container: php:7.4

    steps:
    - working-directory: ./tests
    - run: apt update
    - run: apt install -y wget
    - run: wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
    - run: chmod +x phpunit
    - run: ls
    #- run: php phpunit
