name: PHPUnit

on:
  push:
    branches: [ master ]

defaults:
  run:
    working-directory: tests

jobs:
  build:

    runs-on: ubuntu-latest
    container: php:7.4

    steps:
    - uses: actions/checkout@v2
    - run: |
        apt update
        apt install -y wget
        wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
        chmod +x phpunit
        ls
    #- run: php phpunit
