name: Unit Test

on:
  push:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container: php:7.4
    steps:
      - name: Update APT
      - run: apt update
      - name: Install wget
      - run: apt install -y wget
      - name: CD into test directory
      - run: cd tests
      - name: Download latest PHPUnit
      - run: wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
      - name: Make PHPUnit executable
      - run: chmod +x phpunit
      - name: Run Tests
      - run: php phpunit
