name: Unit Test

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Brace Unit Tests
        run: |
          apt update
          apt install -y wget
          cd tests
          wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
          chmod +x phpunit
          php phpunit
