name: Unit Test

on:
  push:
    branches: [ master ]

jobs:
  phpunit:
    runs-on: ubuntu-latest
    container: php:7.4
    steps:
      - name: Brace Unit Tests
      - run: apt update
      - run: apt install -y wget
      - run: cd tests
      - run: wget -O phpunit https://phar.phpunit.de/phpunit-9.phar
      - run: chmod +x phpunit
      - run: php phpunit
